server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service # id 唯一即可
          uri: lb://userserver # lb 负载均衡，会根据userserver这个服务名去nacos找到对应的服务
          predicates:
            - Path=/user/** # 路径断言，user开头转发到userserver服务
#          filters:
#            - AddRequestHeader=Truth,I am a cool boy!
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      default-filters:
        - AddRequestHeader=Truth,I am a cool boy!
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedMethods:
              - GET
              - POST
            allowCredentials: true
            allowedHeaders: "*"
            allowedOrigins:
              - localhost:8080